spring:
  profiles:
    active:
      - dev
  
---
server:
  port: 9002
    
spring:
  profiles: dev
  application: 
    name: ms-mall-seller-manager-web
    
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
        - bus-refresh
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka.mall.com:7001/eureka  
  instance:
    instance-id: ms-mall-seller-manager-web-9001
    prefer-ip-address: true     #访问路径可以显示IP地址  

swagger:
  enabled: true
  title: ms-mall-seller-manger-API
  description:  商家后端管理系统文档
  base-package:  com.xuxx.ms.mall.manager.controller
  base-path: /**
  exclude-path: /error
  version: $project.version$  

info: 
  app.name: ms-mall
  company.name: xuxingxing
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
health:
  config:
    enabled: true
    
file: 
  server:
  url: http://192.168.1.106
---
# 暂时不启用 test 与 prod