spring:
  profiles:
    active:
      - dev
  
---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.xuxx.ms.mall.brand.entity       # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    
spring:
  profiles: dev
  application: 
    name: ms-mall-brand-service
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
      
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/mall-brand            # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
      
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka.mall.com:7001/eureka  
  instance:
    instance-id: ms-mall-brand-8001
    prefer-ip-address: true     #访问路径可以显示IP地址  

swagger:
  enabled: true
  title: ms-mall-brand-API
  description:  brand API文档
  base-package:  com.xuxx.ms.mall.brand.controller
  base-path: /**
  exclude-path: /error
  version: $project.version$  

info: 
  app.name: ms-mall
  company.name: xuxingxing
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
health:
  config:
    enabled: true
---
server:
  port: 8001                                                #暂时不启动 test 所以和dev 配置一样的

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.xuxx.ms.mall.brand.entity       # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
  
spring:
  profiles: test
  application: 
    name: ms-mall-brand-service
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/mall-brand            # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
      
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka.mall.com:7001/eureka  
  instance:
    instance-id: ms-mall-brand-8001
    prefer-ip-address: true     #访问路径可以显示IP地址  

swagger:
  enabled: true
  title: ms-mall-brand-API
  description:  brand API文档
  base-package:  com.xuxx.ms.mall.brand.controller
  base-path: /**
  exclude-path: /error
  version: $project.version$  

info: 
  app.name: ms-mall
  company.name: xuxingxing
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
health:
  config:
    enabled: true