spring:
  profiles:
    active:
      - dev
---
server:
  port: 7001
spring:
  profiles: dev #开发环境
  application:
    name: ms-mall-eureka-center
eureka: 
  client: 
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去获取注册信息

---
# 暂时不启用 test 与 prod