spring:
  profiles:
    active:
      - dev
  
---
server:
  port: 8003

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    
spring:
  profiles: dev
  application: 
    name: ms-mall-type-template-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/mall-type-template?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  redis:
    host: redis.mall.com    
    port: 6379 
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka.mall.com:7001/eureka  
  instance:
    instance-id: ms-mall-type-template-service-8002
    prefer-ip-address: true     #访问路径可以显示IP地址  

swagger:
  enabled: true
  title: ms-mall-type-template-API
  description:  TypeTemplateAPI文档
  base-package:  com.xuxx.ms.mall.typetemplate.controller
  base-path: /**
  exclude-path: /error
  version: $project.version$  

info: 
  app.name: ms-mall
  company.name: xuxingxing
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
health:
  config:
    enabled: true
---
server:
  port: 8003

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    
spring:
  profiles: test
  application: 
    name: ms-mall-type-template-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/mall-type-template?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  redis:
    host: redis.mall.com   
    port: 6379 
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka.mall.com:7001/eureka  
  instance:
    instance-id: ms-mall-type-template-service-8002
    prefer-ip-address: true     #访问路径可以显示IP地址  

swagger:
  enabled: true
  title: ms-mall-type-template-API
  description:  TypeTemplateAPI文档
  base-package:  com.xuxx.ms.mall.typetemplate.controller
  base-path: /**
  exclude-path: /error
  version: $project.version$  

info: 
  app.name: ms-mall
  company.name: xuxingxing
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
health:
  config:
    enabled: true