spring:
  profiles:
    active:
      - dev
---
server:
  port: 7001
spring:
  profiles: dev #开发环境
  application:
    name: ms-mall-eureka-center
eureka: 
  instance: 
    hostname: eureka.mall.com #eureka服务端的实例名称,由于不能都一样，所以，要修改下 host 进行下映射
  client: 
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去获取注册信息
    service-url: 
      defaultZone: http://eureka.mall.com:7001/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。

---
server:
  port: 7001
spring:
  profiles: test #测试环境,暂时不用，配成和dev一样的
  application:
    name: ms-mall-eureka-center

eureka: 
  instance: 
    hostname: eureka.mall.com #eureka服务端的实例名称,由于不能都一样，所以，要修改下 host 进行下映射
  client: 
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去获取注册信息
    service-url: 
      defaultZone: http://eureka.mall.com:7001/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
